### ISSUE TITLE
Cambiar la posición de `Dashboard` y `Perfil`

### ISSUE THREAD

**Issue by OmarEMC** [portalmybot/issues#17]
¿Qué?
- Poner `Dashboard` por debajo de `Perfil`.

¿Por qué?
- No se, por algún motivo así deben ser las cosas.

Imagen:
![image](https://user-images.githubusercontent.com/51929737/102724651-042b0300-42df-11eb-8d68-3409ad3b0a23.png)

De nada.

**Comment by revelion69** [comment]
super si amiga

**Comment by OmarEMC** [comment]
Muy buena sugerencia, me gusta. 👍

**Comment by CraterMaik** [comment]
Aprobado
