### ISSUE TITLE
Prohibir imágenes de #ayuda-discord_js-1 y 2 en #memes-dev.

### ISSUE THREAD

**Issue by OmarEMC** [portalmybot/issues#19]
### **¿Qué?**
Prohibir cualquier imagen que provenga de los canales #ayuda-discord_js-1 y/o 2 en el canal #memes-dev.

### **¿Por qué?**
1. **0 Gracia**
2. **0 Gracia**
3. Eso es estúpido, si nos ponemos a buscar un mensaje parecido al de ese tipo de imágenes pero de quién envió la imagen encontraremos 10 peores.
4. **0 Gracia**
5. Que estupidez, por que lo hacen.
6. Incita a de cierta manera a que las personas se rían de los que piden ayuda. (esto no aplica para mi, por guapo)

### **¿Qué se puede hacer en caso de que vuelva a pasar?**
1 de 3:
1. Banear a la persona.
2. Banear a la persona.
3. Mutear a la persona.

## **Imagen estúpida, o sea referencial:**
![image](https://user-images.githubusercontent.com/51929737/103043361-a6025800-454a-11eb-9ca0-2081bac16813.png)

De nada.

**Comment by OmarEMC** [comment]
Me gusta 👍

**Comment by NotKirzu** [comment]
¿Y los otros canales de ayuda?

**Comment by OmarEMC** [comment]
> ¿Y los otros canales de ayuda?

Como si en esos la gente se equivocara tanto o hubieran 500 mensajes cada segundo, igual si se quiere ps también se añaden.

**Comment by Awoocado** [comment]
Parte del problema es que algunos usuarios hacen preguntas basicas de js en los canales #ayuda-discord_js-1 y/o 2 cuando la guia indica que necesitas conocimientos antes de hacer un bot

**Comment by OmarEMC** [comment]
> Parte del problema es que algunos usuarios hacen preguntas basicas de js en los canales #ayuda-discord_js-1 y/o 2 cuando la guia indica que necesitas conocimientos antes de hacer un bot

1. Eso que tiene que ver, no importa que pregunta/respuesta hagan.
2. Por que copias mi `#ayuda-discord_js-1 y/o 2` >:p

**Comment by AndreMor8** [comment]
No soy fanático de los memes, mucho menos me gusta que nos estemos burlando de X personas, pero para mí que aplicar esta regla, aparte de **ineficiente para los moderadores**, sería como bloquear esos memes básicos de programación donde te equivocas en algo (lenght en vez de length, falta ";" en X lenguaje)

Porque a la final, nos burlamos de los principiantes.
Osea, ese canal ni existiría

Y como dice Crater, aquí sólo portalmybot.com, no otras secciones del Team ;)
