### ISSUE TITLE
[Bug] Pagina no encontrada en las guias

### ISSUE THREAD

**Issue by Awoocado** [portalmybot/issues#20]
Las guias tienen un boton para navegar entre capitulos. Si estas en el primer capitulo te sale un capitulo adicional antes de este el cual lleva a una pagina no existente

Primer capitulo de la guia:
![IMG_20201224_090956](https://user-images.githubusercontent.com/43632131/103093425-53678100-45c8-11eb-8552-52e920963741.jpg)

Al presionar:
![Screenshot_2020-12-24-09-10-09-364_com android chrome](https://user-images.githubusercontent.com/43632131/103093434-56fb0800-45c8-11eb-93cf-833ddab96c7e.jpg)

**Comment by CraterMaik** [comment]
a bueno
