### ISSUE TITLE
Actualizen a Mybot 

### ISSUE THREAD

**Issue by ghost** [portalmybot/issues#21]
Mybot envia el mensaje de que usen el comando roleme al dm a pesar de que esto ya no se use, esto confunde a muchos usuarios, tambien comandos de economia no se si todos pero la gran mayoria no sirven y aun estan en el help, por ultimo mine sale 2 veces en el help

**Comment by Hyuuh** [comment]
No te preocupes. Igual el bot se debe cambiar de 0 (hablando de code). Por lo que posiblemente será el otro año.
