### ISSUE TITLE
Error con los caracteres con acentos y 'especiales' (en las descripciones de los códigos subidos)

### ISSUE THREAD

**Issue by ghost** [portalmybot/issues#24]
![Screenshot_1](https://user-images.githubusercontent.com/73923005/116824539-c2e21400-ab58-11eb-96d6-6daade853ce8.png)

**Comment by ibnz36** [comment]
No es esto una falta de ` <meta charset="utf-8"/>`?

**Comment by amn1el** [comment]
> No es esto una falta de ` <meta charset="utf-8"/>`?

Casi, es por los caracteres latinos guardados en una base de datos sql y como Cráter usa php seguramente usa mysql y ahi estaria el detalle 
Falta de [mysqli_set_charset](https://www.php.net/manual/es/mysqli.set-charset.php) a `utf8`

**Comment by ibnz36** [comment]
> > No es esto una falta de ` <meta charset="utf-8"/>`?
> 
> Casi, es por los caracteres latinos guardados en una base de datos sql y como Cráter usa php seguramente usa mysql y ahi estaria el detalle
> Falta de [mysqli_set_charset](https://www.php.net/manual/es/mysqli.set-charset.php) a `utf8`

Entonces esto no es solucionable a base de un PR, imagino. Habrá que esperar a que Cater lea esto y lo solucione

**Comment by CraterMaik** [comment]
Si son por la configuración de la base da datos en algunas tablas(MySQL engine), pero ya se esta solucionando en la nueva Base de datos
