### ISSUE TITLE
Contador de votos por usuario en cada bot

### ISSUE THREAD

**Issue by LyricalString** [portalmybot/issues#34]
La idea sería agregar en la base de datos un objeto que contenga el ID del usuario que votó y la cantidad de veces que ha votado. Esto se añadaría al registro actual de la base de datos de bots y sería accesible a través de la API.

Como recomendación debería de guardarse esos datos en la caché y cada cierto tiempo (por ejemplo 30 segundos) subirse a la base de datos, porque si se actualizase cada vez que se votase, podrían haber colapsos con bots grandes, eventos...

**Comment by CraterMaik** [comment]
Si, esta bien pero por el momento en esta versión de MyBOT List es un voto único por BOT, próximamente se agregara esa funcionalidad de voto por x horas y con webhook vía API
