### ISSUE TITLE
Sugerencias para PortalMyBot

### ISSUE THREAD

**Issue by valentinomendoza** [portalmybot/issues#7]
**1.- Sugerencia:** `Tener una "Búsqueda" para buscar usuarios de portalmybot.com`

**Descripción:**

Tener el método de búsqueda de usuarios en portalmybot ya sea por nombre o por ID de discord, si es posible añadir una vista previa cada que mantienes tu "ratón en el perfil del usuario".

**2.- Sugerencia:** `Un logro de Bot Verificado`

**Descripción:**

Logro para los que tienen su Bot Verificado por Discord.

**Comment by CraterMaik** [comment]
Mal usar la plantilla de forma correcta
