### ISSUE TITLE
Cambiar el sistema de los bots

### ISSUE THREAD

**Issue by Fabricio-191** [portalmybot/issues#8]
Bueno, como dice el titulo la idea es cambiar el sistema de los bots, a uno mas eficiente.

### El sistema seria así:

Hay 2 niveles de bots, los "en desarrollo" y los "disponibles para uso publico"

* El nivel "en desarrollo"  

Apenas requiere pruebas en los bots, es mas talvez seria mejor ni hacer pruebas en los bots y solo tomar acción en caso de que ocurra algo cuando el bot esta en el servidor (bucles, spam).  
El bot estará dentro del servidor, pero no aparecerá en la pagina de MyBOT List (o tal vez una sección aparte)

* El nivel "disponibles para uso publico" 

requiere una verificación como la que se hace actualmente o un poco mas exhaustiva, pero aparecerán en la pagina de MyBOT List. Esta verificación al ser un poco mas exhaustiva, llevara tiempo, por lo tanto, tendrá un cooldown

Que variara según la complejidad de los errores, un error muy simple, llevara a un gran cooldown, por que si el bot tiene errores simples, nos da una idea de que esta poco desarrollado y no debería ser publico

Aca amplio un poco mas la idea:

Si uno va a top.gg, hay un canal de texto donde se pueden usar todos los bots, pero uno pone cualquier cosa y el canal se llena de mensajes y eso que tienen la mayoría de los bots muteados, entonces para evitar esto, se me ocurrió que deberíamos mutear a todos los bots, tanto en desarrollo como públicos.

Y hacer un comando, que cualquiera pueda usar (desarrolladores y personas viendo los bots), el cual desmutee a un bot en especifico por 30 mins, entonces cuando uno quiere probar un bot, se asegura que le responda solo ese bot y no 4 o 5 bots

De paso, nos evitamos posibles bucles para todos los bots y las reacciones molestas, lo que haría la verificación mucho mas simple o casi nula

Y sobre el canal de los logs, todavía pienso el que hacer con eso, pero si deberían configurar los permisos para que las personas no puedan hablar en el

**Comment by CraterMaik** [comment]
Me parece perfecto

**Comment by ghost** [comment]
Añadiendo a la idea quiza el comando que desmutea al bot por x tiempo no sea necesario pensando en que hay personas que realmente testean sus bots en esos canales, bueno la idea seria que si el bot tiene un prefix repetido (que otro bot lo tenga) tenga 24 horas para cambiarlo (en el sv), si no lo cambia lo mutean del servidor (Lo mismo afectaria si tiene sistema de leveling sin notificaciones desactivables o reacciones inecesarias)

**Comment by Fabricio-191** [comment]
> Añadiendo a la idea quiza el comando que desmutea al bot por x tiempo no sea necesario pensando en que hay personas que realmente testean sus bots en esos canales, bueno la idea seria que si el bot tiene un prefix repetido (que otro bot lo tenga) tenga 24 horas para cambiarlo (en el sv), si no lo cambia lo mutean del servidor (Lo mismo afectaria si tiene sistema de leveling sin notificaciones desactivables o reacciones inecesarias)

Yo diría que no, teniendo en cuenta que los bots están en desarrollo, así nos evitamos problemas o bucles, aparte que, en tu sistema, si yo desmuteo un bot que estaba muteado por un prefix repetido, el bot que no esta muteado con ese prefix también va a responder

Y encima, seria molesto para los desarrolladores el tener que agregar un sistema de prefix personalizados solo por eso

**Comment by Awoocado** [comment]
> Yo diría que no, teniendo en cuenta que los bots están en desarrollo
Se supone que si los usuarios registran a su bot en MyBOT List es porque ya estan listos para usar en público. Invitar un bot que no esta listo solo traerá más inconvenientes.

> la idea seria que si el bot tiene un prefix repetido (que otro bot lo tenga) tenga 24 horas para cambiarlo (en el sv), si no lo cambia lo mutean del servidor (Lo mismo afectaria si tiene sistema de leveling sin notificaciones desactivables o reacciones inecesarias)
No estoy de acuerdo, esto seria un cambio del server, no de la pagina web

**Comment by Fabricio-191** [comment]
> > Yo diría que no, teniendo en cuenta que los bots están en desarrollo
> > Se supone que si los usuarios registran a su bot en MyBOT List es porque ya estan listos para usar en público. Invitar un bot que no esta listo solo traerá más inconvenientes.
> 
> > la idea seria que si el bot tiene un prefix repetido (que otro bot lo tenga) tenga 24 horas para cambiarlo (en el sv), si no lo cambia lo mutean del servidor (Lo mismo afectaria si tiene sistema de leveling sin notificaciones desactivables o reacciones inecesarias)
> No estoy de acuerdo, esto seria un cambio del server, no de la pagina web

A ver... la propuesta original mía también lleva a un cambio del server, además del de la pagina web.
Así que lo que dices no tiene sentido

**Comment by Awoocado** [comment]
> A ver... la propuesta original mía también lleva a un cambio del server, además del de la pagina web.
> Así que lo que dices no tiene sentido

Le decia a @ILuckZ =w=

**Comment by Fabricio-191** [comment]
> > A ver... la propuesta original mía también lleva a un cambio del server, además del de la pagina web.
> > Así que lo que dices no tiene sentido
> 
> Le decia a @ILuckZ =w=

Y yo te dije que lo que le dijiste no tiene sentido

**Comment by CraterMaik** [comment]
Nuevo MyBOT List https://portalmybot.com/list/
